### ISSUE TITLE
gittime.io SPAM

### ISSUE THREAD

**Issue by aleemb** [StephenOTT/GitHub-Time-Tracking#12]
I got the following spam:

```
Eugene from GitTime <hi@gittime.io>

Hi,

I noticed on GitHub that you interested in time tracking using Git (since you've starred StephenOTT/GitHub-Time-Tracking).

I'm building an application that can help you to track time right from commit messages and to generate reports/invoices from that data.

Everything is already set up for you. Just visit https://gittime.io and login with your GitHub account (@aleemb).

Your questions and feedback would be much appreciated.

Thanks!
Eugene

P.S. This is the last email you'll receive from me, unless you claim your account.
```

This is not an issue per se but it's likely someone is spamming followers of this repo and should be denounced.

**Comment by StephenOTT** [comment]
Ha! -- I will add a message to the readme.  I have also emailed Eugene.

**Comment by StephenOTT** [comment]
Message has been added to readme https://github.com/StephenOTT/GitHub-Time-Tracking/commit/6a627b921edb4a57b0d2572cf15b07dd58dc4534

**Comment by StephenOTT** [comment]
Thanks @aleemb

**Comment by StephenOTT** [comment]
Gittime should not be emailing anyone else from the star/follow list for this repo.  Please let me know if it happens again.  I will remove the warning on the readme page unless it happens again :smile:

**Comment by aleemb** [comment]
​Sounds good. On that note, it's probably a good idea to set this up as a
service yourself since you did the leg work.​

Aleem

**Comment by StephenOTT** [comment]
@aleemb ya been meaning to get around to it.  Just never had the time with other projects.  Would like to rebuild it as a smaller footprint as as a meteor-Angular app or maybe a Voltrb app
